#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

err() {
    echo "Error: $1"
    exit 1
}

echo "Running pre-commit hook!"

make || err "Make command failed!"

exit 0
